### ISSUE TITLE
Discord user deafen triggers "Today's Work Session" Prompt

### ISSUE THREAD

**Issue by SeanningTatum** [twounfocused/digital-coworking#1]
**Describe the bug**
Discord user deafen triggers "Today's Work Session" Prompt

**To Reproduce**
1. Join voice channel 
2. Get "Today's Work Session" Prompt
3. Wait for approximately 5 minutes to wait for the "timeout"
4. Deafen yourself
5. Get "Today's Work Session" Prompt again

**Expected behavior**
Discord User should not be prompted when they deafen themselves

**Screenshots**
<img width="705" alt="image" src="https://user-images.githubusercontent.com/26712061/233832931-b95de44a-d00b-4565-88ab-454d6557e995.png">

**Additional context**
https://github.com/twounfocused/digital-coworking/blob/9d0f72ff9423fc7d025d0f07cc7020e15340807e/src/eventHandlers/VoiceStateUpdate.ts#L63-L73

**Comment by sekunho** [comment]
It also triggers with status changes like from away to active
